name: Build and publish RaspAP images

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  build-raspap-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: "32-bit"
            pi_gen_version: "master"
          - arch: "64-bit"
            pi_gen_version: "arm64"
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm,arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Add RaspAP Stage
        run: sh ./.github/scripts/add-raspap-stage.sh

      - name: Build RaspAP Image
        id: build
        uses: RaspAP/pi-gen-action@v1.11.0
        with:
          image-name: "raspap-trixie-${{ matrix.arch == '32-bit' && 'armhf' || 'arm64' }}-lite-${{ github.event.inputs.tag || github.ref_name }}"
          enable-ssh: 1
          stage-list: stage0 stage1 stage2 ./stage-raspap
          verbose-output: true
          pi-gen-version: ${{ matrix.pi_gen_version }}
          pi-gen-repository: RaspAP/pi-gen
          pi-gen-release: "Raspberry Pi reference"
          release: "trixie"
          compression: zip
          compression-level: 6
          locale: en_GB.UTF-8
          hostname: raspberrypi
          keyboard-keymap: gb
          keyboard-layout: "English (UK)"
          timezone: Europe/London
          username: pi
          disable-first-boot-user-rename: 0
          pubkey-only-ssh: 0
          export-last-stage-only: true
          enable-noobs: false
          increase-runner-disk-size: false
          pi-gen-dir: pi-gen
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: "raspap-trixie-${{ matrix.arch == '32-bit' && 'armhf' || 'arm64' }}-lite-${{ github.event.inputs.tag || github.ref_name }}.img.zip"
          file: ${{ steps.build.outputs.image-path }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.tag || github.ref }}
          overwrite: true
          
  torrent:
    needs: build-raspap-image
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate torrents for release
        uses: devopsx/action-torrent@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          local: false
